"""init embedding

Revision ID: 1fa1c80bab80
Revises: 5be7313fd041
Create Date: 2026-04-25 21:47:10.944421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector.sqlalchemy  # Bu satırı ekleyin

# revision identifiers, used by Alembic.
revision: str = '1fa1c80bab80'
down_revision: Union[str, Sequence[str], None] = '5be7313fd041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('arxiv_articles', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arxiv_articles', 'embedding')
    # ### end Alembic commands ###
