"""update_schema_for_all_articles

Revision ID: 2094e58d9e01
Revises: 1fa1c80bab80
Create Date: 2026-04-29 14:25:57.010125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '2094e58d9e01'
down_revision: Union[str, Sequence[str], None] = '1fa1c80bab80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('abstract_text', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('primary_category', sa.String(length=100), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_external_id'), 'articles', ['external_id'], unique=True)
    op.create_index(op.f('ix_articles_source'), 'articles', ['source'], unique=False)
    op.drop_index(op.f('ix_arxiv_articles_arxiv_id'), table_name='arxiv_articles')
    op.drop_table('arxiv_articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arxiv_articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('arxiv_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('abstract_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('publish_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('authors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pdf_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('primary_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('arxiv_articles_pkey'))
    )
    op.create_index(op.f('ix_arxiv_articles_arxiv_id'), 'arxiv_articles', ['arxiv_id'], unique=True)
    op.drop_index(op.f('ix_articles_source'), table_name='articles')
    op.drop_index(op.f('ix_articles_external_id'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
